### PR TITLE
CSV export

### LINKED ISSUE #18: CSV export
Make it possible to export the result of a an aggregation as CSV. Suggested API:

``` php
$result = $collection->aggregate($aggregationBuilder->build());
$csvBuilder = new CSVExport();
$csvBuilder->exportToFile($result, 'result.csv');
```

### PR DESCRIPTION
**Pull request by RonRademaker**
This PR fixed #18

### CODE REVIEW

**Comment by gisoconnectholland** [comment]
This was not what I suggested in #18. What I meant is: Why should this library have any concerns about csv?. This thing can aggregate mongo. You can use the csv library in your project to handle the resultdata of this library.

**Comment by RonRademaker** [comment]
I think it's useful if this library can export in various formats, not only return an array. Why should anyone have to make functions (using libraries or not) to export the results again and again. The csv library also has methods to export to XML and JSON, so this can be easily extended to support more formats.

**Comment by gisoconnectholland** [comment]
I think having good support in a DRY way is good. I just do not think it should be in this library. Maybe a separate one? The fact the mentioned csv library supports other formats as output is because it is also a csv reader/converter.

**Comment by RonRademaker** [comment]
A general purpose exporter library sounds goods. I'll still pull this PR because of deadline issues, but will start on a separate component for exporting soon. There will then be an Exporter in this package that uses an ExporterInterface object from the separate component to do the actual work.

**Comment by gisostallenberg** [comment]
For mongo aggregation data I presume (and hope).

**Comment by RonRademaker** [comment]
Something like:

``` php
$result = $collection->aggregate($aggregation);
$exporter = new Exporter(new CSVExporter()); // CSVExport is in a separate component, Exporter is in this component
$export->export($result, $file); // unsets id objects, transforms MongoDate to strings, etc and passes the array and $file (and other optional arguments perhaps) to the CSVExporter
```

**Pull request merged**
